server:
  port: ${PORT}

logging:
  level:
    org.springframework.security: trace

spring:
  application:
    name: SSOServer
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: ${PG_URL}
    username: ${PG_USER}
    password: ${PG_PASS}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

root-user-name: ${ROOT_USER_NAME}
root-user-password: ${ROOT_USER_PASS}

admin-user-name: ${ADMIN_USER_NAME}
admin-user-password: ${ADMIN_USER_PASS}

user-name: ${USER_NAME}
user-password: ${USER_PASS}
